
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cal_app
  name: calculator
  namespace: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cal_app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cal_app
    spec:
      containers:
      - image: moveho/calculator
        name: calculator
        resources: {}
status: {}
